version: '3.8'

services:
  db-grafica:
    image: postgres:15-alpine
    container_name: db-grafica
    environment:
      POSTGRES_DB: grafica_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db-grafica-data:/var/lib/postgresql/data
    networks:
      - grafica-network

  postgres-keycloak:
    image: postgres:15-alpine
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    volumes:
      - postgres-keycloak-data:/var/lib/postgresql/data
    networks:
      - grafica-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    # Comando simplificado sem o prefixo /auth
    command: start-dev --hostname-strict=false
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: "true"
    ports:
      - "8180:8080"
    depends_on:
      - postgres-keycloak
    networks:
      - grafica-network

  api-grafica:
    build: .
    container_name: api-grafica
    ports:
      - "8080:8080"
    extra_hosts:
      - "localhost:host-gateway"
    depends_on:
      - db-grafica
      - keycloak
    networks:
      - grafica-network

volumes:
  db-grafica-data:
  postgres-keycloak-data:

networks:
  grafica-network:
    driver: bridge